### ISSUE TITLE
Question about normalization calculations

### ISSUE THREAD

**Issue by nearinj** [mcalgaro93/sc2meta#1]
Hello,

First of all I really enjoyed reading your paper. It was an excellent analysis that gave me a lot of insight into the various tools. I've been doing a similar analysis so I was interested in looking at your evaluation functions. I'm trying to figure out what this line of code is doing though:

`normFacts <- paste("NF", normFacts, sep = ".")
 NFs = get_variable(physeq, normFacts)
    NFs = NFs/exp(mean(log(NFs)))`

 I understand that you are getting the normalization factors from the various methods (TMM, etc.) using the calcNormFactors, however, I don't understand why these factors are then further changed in the last part the of code! I haven't seen this done in other edgeR tutorials so any guidance would be really appreciated. 

Thanks, Jacob Nearing

**Comment by mcalgaro93** [comment]
Hi Jacob,
I'm glad to know you enjoyed the reading and I thank you for the kind words
of appreciation!
You have a sharp eye 😉, I took that specific code from a great work of
Hawinkel et al. (code:
https://users.ugent.be/~shawinke/ABrokenPromise/03_diffAbundDetect.html).
Indeed, they established a really inspiring benchmarking framework for
differential abundance detection methods, that's why I decided to start
from there instead of starting from scratch. The exp(mean(log(NFs))) is the
geometric mean of the normalization factors. The results are not affected
by this further change (because it is a simple "multiplication by a
constant") however the authors suggest to use it in order to facilitate
fitting (It is mentioned as a comment under the function negBinTestDESeq2).
I have not verified this last statement by stressing the normalization
process with and without that further change, I simply kept it.

Don't hesitate to contact me if you have any doubts or other questions.
Thank you for your question.

Best regards,

Matteo Calgaro
PhD Student,
Dept. of Biotechnologies,
University of Verona


Il giorno mer 2 set 2020 alle ore 20:38 nearinj <notifications@github.com>
ha scritto:

**Comment by mcalgaro93** [comment]
Hi Jacob,
I'm glad to know you enjoyed the reading and I thank you for the kind words of appreciation!
You have a sharp eye 😉, I took that specific code from a great work of Hawinkel et al. (code: https://users.ugent.be/~shawinke/ABrokenPromise/03_diffAbundDetect.html). Indeed, they established a really inspiring benchmarking framework for differential abundance detection methods, that's why I decided to start from there instead of starting from scratch. The `exp(mean(log(NFs)))` is the geometric mean of the normalization factors. The results are not affected
by this further change (because it is a simple "multiplication by a constant") however the authors suggest to use it in order to facilitate fitting (it is mentioned as a comment under the function `negBinTestDESeq2`). I have not verified this last statement by stressing the normalization process with and without that further change, I simply kept it. 

Don't hesitate to contact me if you have any doubts or other questions.
Thank you for your question.

Best regards,
Matteo Calgaro

**Comment by nearinj** [comment]
Thanks for getting back to me so quick. I'll take a look at the link above. Something I have notice while testing out limma_voom_TMM is that the normalization step (calcNormFactors) doesn't seem to be deterministic when the sampling order is shuffled. 

Me and a colleague have noticed that if you take a count table and shuffle the column order the normalization factors can be drastically different for the same sample. Furthermore, we noticed that this can have an impact on the downstream number of significant hits found be the tool. We have tested this on two different 16S datasets and received similar results. Though we are not sure if this is due to the sparsity/distrubition of 16S data. 

Below is a boxplot showing the correlation between the normalization factors calculated from 100 count tables with randomly shuffled column orders. The first shows the correlation between the 100 shuffles and the original order and the second shows the correlation between all 100 random shuffles. Overall you can see that while there is a moderate correlation these differences do seem to impact the downstream results.

![image](https://user-images.githubusercontent.com/31660222/92149191-0cc10180-edf4-11ea-8723-855e8667a0d2.png)

Have you come across this before?

**Comment by mcalgaro93** [comment]
That's quite strange. I tried to build a toy example which compares shuffled results. I didn't notice such behaviours. Have you shuffled both the otu_table and sam_data slots of the phyloseq object?

```
# Load functions
source("./eval_functions.R")
# Load data
load("./data/16Sdatasets_for_replicability_filtered.RData")
# Example dataset
ps <- ps_list_16S$Subgingival_Supragingival

# Relabelling the comparison variable
ps@sam_data$grp <- factor(ps@sam_data$HMP_BODY_SUBSITE,
                          levels = c("Subgingival Plaque","Supragingival Plaque"),
                          labels = c("grp1","grp2"))

# edgeR TMM normalization on unshuffled data
physeq_unshuffled <- normEdgeR(ps,"TMM")

# Random shuffling
set.seed(123)
shuffle <- sample(1:nsamples(ps),size = nsamples(ps),replace = FALSE)
# Create the shuffled phyloseq object
ps_shuffled <- ps
# Remember to shuffle both otu_table and sample_data slots
ps_shuffled@otu_table <- ps_shuffled@otu_table[,shuffle]
ps_shuffled@sam_data <- ps_shuffled@sam_data[shuffle,]

# edgeR TMM normalization on shuffled data
physeq_shuffled <- normEdgeR(ps_shuffled,"TMM")

# Check if the Normalization Factors are equal
head(data.frame("Unshuffled_NFs" = physeq_unshuffled@sam_data$NF.TMM,
                "Shuffled_NFs" = physeq_shuffled@sam_data$NF.TMM[names(physeq_unshuffled@sam_data$NF.TMM)]))

# Let's try the entire pipeline

unshuffled_DA <- limma_voom(physeq_unshuffled,normFacts = "TMM")
unshuffled_DA_names <- rownames(unshuffled_DA$pValMat[unshuffled_DA$pValMat[,2]<0.05,])

shuffled_DA <- limma_voom(physeq_shuffled,normFacts = "TMM")
shuffled_DA_names <- rownames(shuffled_DA$pValMat[shuffled_DA$pValMat[,2]<0.05,])

# Count the differences
sum(shuffled_DA_names != unshuffled_DA_names)
```

**Comment by nearinj** [comment]
Hi Matteo,

I spent some time troubleshooting the odd results I have been getting and think have found the issue. I tested nine separate datasets (the 3 16S datasets in this repo along with 6 previously published datasets). I have found that the three datasets in this repo do not suffer from the reproducible issue, however, other 16S datasets do. 


I found that after 100 random prefumations of the column orders of these nine datasets four other them give consist normalization factors from the normedgeR function but five of them do not. 

![image](https://user-images.githubusercontent.com/31660222/92525817-e2f44a00-f1fa-11ea-8019-1789a7ba7ca7.png)

Investigating the differences in these datasets I found that the datasets that failed to give reproducible normalization factors also had the highest sparsity. 

![image](https://user-images.githubusercontent.com/31660222/92525918-0d460780-f1fb-11ea-8dd6-ad8c2fbdd71c.png)

To investigate this further I took three datasets that didn't work (Biscuit, Chemerin, CRC_baxter) and filtered the ASV table based on the prevalence of features. Prevalence filtering at 10%, 5% and 3% revealed that as the matrix because less sparse the results become reproducible.

![image](https://user-images.githubusercontent.com/31660222/92526405-d0c6db80-f1fb-11ea-85ee-a94863361da9.png)


![image](https://user-images.githubusercontent.com/31660222/92526341-af65ef80-f1fb-11ea-8ad3-c025b4789c82.png)

This indicates to me that TMM normalization should not preformed on matrix's that have sparsity greater than >0.78 as the normalization factors may not be reproducible. I would love to hear your thoughts on this and whether you find this in your own hands. I have included the datasets along with an rmarkdown file contain all the code for the analysis that I did.

https://www.dropbox.com/sh/6fo3fipyc0p36f3/AACnNhDmOk5U285g_u9g0fTba?dl=0

Thanks for looking into this.

Jacob Nearing
Dalhousie University
Langille Lab

**Comment by mcalgaro93** [comment]
Dear Jacob,
thank you for your troubleshooting. I tried your code and now I understand your results. 
In the following link you can find the original `calcNormFactors` code: https://rdrr.io/bioc/edgeR/src/R/calcNormFactors.R . I tried it directly on your datasets and the problem persists. As you said, it is probably due to the sparsity but if you want to specifically identify what is causing the problem I suggest you to debug the original edgeR code or ask to the edgeR authors.

I've never experienced it in my data because for differential abundance analysis I usually use the filtered count table obtained by the following function:`filter_taxa(ps,function(x) sum(x>10)>1,1)`. In this way I am sure that all the taxa are present in more than 1 sample and with more than 10 counts. Sparsity is also reduced by doing so. I also use the filter by prevalence but usually the first filter is enough. The phyloseq objects in `./data/16Sdatasets_for_replicability_filtered.RData` were already filtered, that's why the issue didn't arise. 

The filtering choice is arbitrary, however you have to think about what the data are intended for. In my case, they served to make the counts comparable between samples and then a negative binomial should fit each taxon count distribution. For these reasons I needed more than 1 positive counts for each taxon (the more, the better for the model estimation). Taxa with very low values, together with a sparse presence in the samples, only bring unwanted variability. The models hardly handle those taxa and the results on them are not trustworthy. However, I don't think this is an excuse for normalization factors not to be reproducible. In the next months I will insert some checks in the code to prevent too sparse count tables from being handled. Thank you for noticing it. 

I remain at your disposal for any clarification.

**Comment by nearinj** [comment]
Hi Matteo,

If your interested in how this was resolved you can check out my post on bioconductor.

https://support.bioconductor.org/p/133921/#133922

Thanks for taking the time with this issue and best of luck in your future work.
